sudo: required
services:
  - docker

before_install:
  - docker build -t kirill1/docker-react -f Dockerfile.dev .

script:
  - docker run kirill1/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-777520768008"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_ID"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"